// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr1EbD-gc0u3FJRIkbV-siqMcBHQCO1yM',
    appId: '1:836869804362:web:a65f8385568beb0999b1b3',
    messagingSenderId: '836869804362',
    projectId: 'tracktag-bb931',
    authDomain: 'tracktag-bb931.firebaseapp.com',
    storageBucket: 'tracktag-bb931.firebasestorage.app',
    measurementId: 'G-LP9F1NQ44M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCV2pwb07tqDkbcw61ltDdS8YvQYpxVq0',
    appId: '1:836869804362:android:4491f1f2f783fe3e99b1b3',
    messagingSenderId: '836869804362',
    projectId: 'tracktag-bb931',
    storageBucket: 'tracktag-bb931.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd9dKzC2FiU8Van_FllJ1hDT38z-nkGcI',
    appId: '1:836869804362:ios:c36ee5f075c9b70799b1b3',
    messagingSenderId: '836869804362',
    projectId: 'tracktag-bb931',
    storageBucket: 'tracktag-bb931.firebasestorage.app',
    iosBundleId: 'com.example.trackTag',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd9dKzC2FiU8Van_FllJ1hDT38z-nkGcI',
    appId: '1:836869804362:ios:c36ee5f075c9b70799b1b3',
    messagingSenderId: '836869804362',
    projectId: 'tracktag-bb931',
    storageBucket: 'tracktag-bb931.firebasestorage.app',
    iosBundleId: 'com.example.trackTag',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr1EbD-gc0u3FJRIkbV-siqMcBHQCO1yM',
    appId: '1:836869804362:web:753fb2f85f2bb15a99b1b3',
    messagingSenderId: '836869804362',
    projectId: 'tracktag-bb931',
    authDomain: 'tracktag-bb931.firebaseapp.com',
    storageBucket: 'tracktag-bb931.firebasestorage.app',
    measurementId: 'G-S73K2758F7',
  );

}